version: '2'

services:
  backend:
    build: ./backend/eventmanager
    restart: unless-stopped
    container_name: frontend
    ports:
    - "80:80"
    networks:
    - polytech

  frontend:
    build: ./frontend/eventmanager
    restart: unless-stopped
    container_name: backend
    ports:
    - "8080:8080"
    depends_on:
    - mariadb
    networks:
    - polytech

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: on-failure
    volumes:
    - mariadb:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=glopglop
    - MYSQL_DATABASE=db
    - MYSQL_USER=pifou
    - MYSQL_PASSWORD=pasglop
    networks:
    - polytech

networks:
  polytech:

volumes:
  mariadb:
